import { fonts } from './fonts'
import { Providers } from './providers'

export const metadata = {
  title: 'CampusLots | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={fonts.rubik.variable}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
